#!/usr/bin/python3

import argparse as ap
import sys 

parser = ap.ArgumentParser()

parser.add_argument('input_file', nargs='?', type=ap.FileType('r'), default=sys.stdin)

args = parser.parse_args()

line_count, word_count, char_count  = 0, 0, 0

for line in args.input_file:
    line_count += 1

    for word in line.split():
        word_count += 1

        for char in word:
            char_count += 1

char_count += word_count
char_count += line_count

print('{} {} {}'.format(line_count, word_count, char_count))


